# Generated by Django 3.2.6 on 2021-08-09 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('r', 'Red'), ('b', 'Blue'), ('g', 'Green'), ('y', 'Yellow'), ('w', 'White')], max_length=1)),
                ('long', models.IntegerField(default=10)),
                ('ctype', models.CharField(choices=[('l', 'Light'), ('h', 'Heavy')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ncode', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('long', models.IntegerField(default=10)),
                ('state', models.CharField(choices=[('1', 'Tehran'), ('2', 'Mashhad'), ('3', 'Qom'), ('4', 'Shiraz'), ('5', 'Rasht'), ('6', 'Tabriz')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TollStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pay', models.IntegerField(default=1000)),
                ('state', models.CharField(choices=[('1', 'Tehran'), ('2', 'Mashhad'), ('3', 'Qom'), ('4', 'Shiraz'), ('5', 'Rasht'), ('6', 'Tabriz')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('paid_date', models.DateTimeField(verbose_name='paid date')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.car')),
                ('toll_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.tollstation')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('loaded_date', models.DateTimeField(verbose_name='loaded date')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver'),
        ),
    ]
