# Generated by Django 3.2.6 on 2021-08-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='long',
            new_name='length',
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('r', 'Red'), ('b', 'Blue'), ('l', 'Black'), ('w', 'White')], max_length=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='ctype',
            field=models.CharField(choices=[('s', 'small'), ('b', 'big')], max_length=1),
        ),
    ]
