# Generated by Django 3.2.6 on 2021-08-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_alter_driver_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='length',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='driver',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
