# Generated by Django 3.2.6 on 2021-08-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_auto_20210810_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='length',
            field=models.FloatField(default=10, null=True),
        ),
    ]
