# Generated by Django 3.2.6 on 2021-08-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_alter_car_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tollstation',
            old_name='pay',
            new_name='toll_per_cross',
        ),
        migrations.AlterField(
            model_name='car',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tollstation',
            name='state',
            field=models.CharField(max_length=1),
        ),
    ]
