# Generated by Django 3.2.6 on 2021-08-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_auto_20210812_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='length',
            new_name='lengh',
        ),
    ]
