# Generated by Django 3.2.6 on 2021-08-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_rename_length_car_lengh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='lengh',
            new_name='length',
        ),
    ]
