# Generated by Django 3.2.6 on 2021-08-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_rename_lengh_car_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='color',
            new_name='colo',
        ),
    ]
