# Generated by Django 3.2.6 on 2021-08-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0010_rename_color_car_colo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='colo',
            new_name='color',
        ),
    ]
