# Generated by Django 3.2.6 on 2021-08-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0011_rename_colo_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='load_valume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_toll_paid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
