# Generated by Django 3.2.6 on 2021-08-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0012_auto_20210814_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='state',
            field=models.CharField(max_length=30),
        ),
    ]
