# Generated by Django 3.2.6 on 2021-08-22 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0014_node'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='point',
            new_name='location',
        ),
        migrations.AddField(
            model_name='node',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.car'),
        ),
        migrations.AddField(
            model_name='node',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date'),
        ),
    ]
