# Generated by Django 3.2.6 on 2021-08-22 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0015_auto_20210822_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.car'),
        ),
    ]
