# Generated by Django 3.2.6 on 2021-08-22 11:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0016_alter_node_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
