# Generated by Django 3.2.6 on 2021-08-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0017_alter_node_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
    ]
