# Generated by Django 3.2.6 on 2021-08-22 12:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0018_delete_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('date', models.DateTimeField(null=True, verbose_name='date')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.car')),
            ],
        ),
    ]
