# Generated by Django 3.2.6 on 2021-08-22 18:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0019_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='long',
        ),
        migrations.RemoveField(
            model_name='road',
            name='state',
        ),
        migrations.AddField(
            model_name='road',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='road',
            name='width',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
