# Generated by Django 3.2.6 on 2021-08-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0020_auto_20210822_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
