# Generated by Django 3.2.6 on 2021-08-24 07:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0021_alter_road_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tollstation',
            name='state',
        ),
        migrations.AddField(
            model_name='tollstation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
